---
title: "crop_data"
author: "Millie Chapman"
date: "7/20/2020"
output: github_document
---

Set Up Direct Access the LP DAAC Data Pool with R
```{r}
# Load packages into R
library(sys)
library(getPass)
library(httr)
```

Set up environment
```{r}
usr <- file.path(Sys.getenv("USERPROFILE"))  # Retrieve user directory (for netrc file)
if (usr == "") {usr = Sys.getenv("HOME")}    # If no user profile exists, use home directory
netrc <- file.path(usr,'.netrc', fsep = .Platform$file.sep) # Path to netrc file

# ----------------------------------CREATE .NETRC FILE-------------------------------------------- #
# If you do not have a  .netrc file with your Earthdata Login credentials stored in your home dir,
# below you will be prompted for your NASA Earthdata Login Username and Password and a netrc file
# will be created to store your credentials (home dir). Create an account at: urs.earthdata.nasa.gov
if (file.exists(netrc) == FALSE || grepl("urs.earthdata.nasa.gov", readLines(netrc)) == FALSE) {
  netrc_conn <- file(netrc)

  # User will be prompted for NASA Earthdata Login Username and Password below
  writeLines(c("machine urs.earthdata.nasa.gov",
               sprintf("login %s", getPass(msg = "Enter NASA Earthdata Login Username \n (or create an account at urs.earthdata.nasa.gov):")),
               sprintf("password %s", getPass(msg = "Enter NASA Earthdata Login Password:"))), netrc_conn)
  close(netrc_conn)
}
```

Get file list - example africa folder of global croplands data (is there a nicer way to do this?)
```{r}
library(RCurl)
library(XML)
url<-"https://e4ftl01.cr.usgs.gov/MEASURES/GFSAD30AFCE.001/2013.01.01/"
url2<-getURL(url)
parsed<-htmlParse(url2)
files_all<-xpathSApply(parsed,path = "//a",xmlGetAttr,"href")
files<- Filter(function(x) any(grepl("*.tif", x)), files_all)
```

Connect to data pool and download files
```{r, message=FALSE}
# Loop through all files
for (i in 1:length(files)) {
  filename <-  tail(strsplit(files[i], '/')[[1]], n = 1) # Keep original filename

  # Write file to disk (authenticating with netrc) using the current directory/filename
  response <- GET(paste("https://e4ftl01.cr.usgs.gov/MEASURES/GFSAD30AFCE.001/2013.01.01/", files[i]), write_disk(paste("/nfs/agroforestry-data/cropland/", filename), overwrite = TRUE), progress(),
                  config(netrc = TRUE, netrc_file = netrc), set_cookies("LC" = "cookies"))
}
```

```{r}

```


